server:
  port: 8080
spring:
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://localhost:3306/hpm?autoReconnect=true&characterEncoding=utf8&useUnicode=yes&serverTimezone=Asia/Seoul;
    username: root
    password: root
    platform: mariadb
    driver-class-name: org.mariadb.jdbc.Driver
    dbcp2:
      validation-query: select 1
  jpa:
    generate-ddl: true  #ddl을 자동으로 생성한다.
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL55Dialect #데이터 베이스 방언 각각 디비별 고유한 기능으로 대체시키는 설정
  jackson:
    serialization:
      fail-on-empty-beans: false
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace
uploads:
  resouceImgPath : C:/uploads/resImg
  filePath: C:/uploads/file
security:
  oauth2:
    jwt:
      signkey: 123@#$
